apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cloith-platform
build:
  artifacts:
    - image: docker.io/cloith/frontend
      context: apps/chatter/frontend
      sync:
        manual:
          - src: 'src/**/*.jsx'
            dest: .
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.css'
            dest: .
    - image: docker.io/cloith/backend
      context: apps/chatter/backend
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    - infrastructure-collections/k3s-ngf-1c-1n-dev/namespaces/mqtt-broker.yaml  # Namespace first!
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/mosquitto-config.yaml
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/mosquitto-dev.yaml
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/reference-grant.yaml # Permission next
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/chatter-route.yaml   # Route last
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/frontend-dev.yaml
      - infrastructure-collections/k3s-ngf-1c-1n-dev/manifest/backend-dev.yaml
deploy:
  kubectl: {}