{
    "passwordHistory": [],
    "revisionDate": None,
    "creationDate": None,
    "deletedDate": None,
    "archivedDate": None,
    "organizationId": None,
    "collectionIds": None,
    "folderId": None,
    "type": 1,
    "name": "Item name",
    "notes": "Some notes about this item.",
    "favorite": False,
    "fields": [],
    "login": None,
    "secureNote": None,
    "card": None,
    "identity": None,
    "sshKey": None,
    "reprompt": 0,
}
