---
# PLAY 1: The Safety Gate (Self-contained)
- name: "Safety Confirmation"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: "confirm_nuke"
      prompt: "WARNING: This will wipe your VPS. Type 'RECREATE' to continue"
      private: no
  tasks:
    - name: "Validate Confirmation"
      ansible.builtin.fail:
        msg: "Run aborted. You did not type 'RECREATE' correctly."
      when: confirm_nuke != "RECREATE"

# PLAY 2: Run the Provisioning (Imported)
- name: "Nuke and Reinstall VPS"
  ansible.builtin.import_playbook: 00-infra-bootstrap/recreate-vps.yml

# reload new values for PLAY 3
- name: "Refresh Inventory to pick up the new IP"
  hosts: localhost
  tasks:
    - name: "Reload inventory file from disk"
      ansible.builtin.meta: refresh_inventory

# PLAY 3: Run the Setup (Imported)
- name: "System prep and Hardening"
  ansible.builtin.import_playbook: 00-infra-bootstrap/system-prep.yml

# reload new values for PLAY 4
- name: "Refresh Inventory to pick up the new IP"
  hosts: localhost
  tasks:
    - name: "Reload inventory file from disk"
      ansible.builtin.meta: refresh_inventory

# PLAY 4: K3s installation (Imported)
- name: "K3s Installation"
  ansible.builtin.import_playbook: 00-infra-bootstrap/k3s-install.yml

