---
- name: "Interactive Bitwarden Identity"
  hosts: localhost
  connection: local
  gather_facts: false

  vars_prompt:
    - name: bw_email
      prompt: "Enter Bitwarden Email"
      private: false
    - name: bw_password
      prompt: "Enter Bitwarden Master Password"
      private: true

  tasks:
    - name: Authenticate and Sync
      # Using 'bw login' directly allows it to prompt if needed, 
      # but we can pass the email/pass for a single-flow experience.
      command: bw login {{ bw_email }} {{ bw_password }} --raw
      register: login_raw
      # We ignore failures if already logged in
      failed_when: 
        - login_raw.rc != 0 
        - "'already logged in' not in login_raw.stderr"
      changed_when: false
      no_log: true

    - name: Get Session Key (Unlock)
      command: bw unlock {{ bw_password }} --raw
      register: bw_session_token
      no_log: true
      changed_when: false

    - name: Use Secret (Example)
      debug:
        msg: "Retrieved secret: {{ lookup('pipe', 'BW_SESSION=' + bw_session_token.stdout + ' bw get item my-tailscale-key | jq -r .notes') }}"
      no_log: true