apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cloith-platform
build:
  artifacts:
    - image: docker.io/cloith/chatter-frontend
      context: ../../apps/chatter/frontend
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
          - src: 'index.html'
            dest: .
    - image: docker.io/cloith/chatter-backend
      context: ../../apps/chatter/backend
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: docker.io/cloith/resend
      context: ../../shared-services/resend
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: docker.io/cloith/firebase-backend
      context: ../../auth-services/firebase/firebase-backend
      sync:
        manual:
          # Sync all Go files in the root or subfolders
          - src: '**/*.go'
            dest: .
          # Sync the Air config if you make changes to how it watches
          - src: '.air.toml'
            dest: .
manifests:
  kustomize:
    paths:
    # 1. Setup everything first
    - 01-platform-setup

    # 2. Secrets
    - 02-platform-secrets/*.yaml

    # 3. Applications
    - 03-platform-deployments/**/*.yaml

    # 4. Routes
    - 04-platform-routes/*.yaml

deploy:
  kubectl: {}