apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cloith-platform
build:
  artifacts:
    - image: docker.io/cloith/frontend
      context: apps/chatter/frontend
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
          - src: 'index.html'
            dest: .
    - image: docker.io/cloith/backend
      context: apps/chatter/backend
      sync:
        manual:
          - src: '**/*.js'
            dest: .
manifests:
  rawYaml:
    # 1. Namespaces & Infrastructure
    - platform-setup/namespaces/*.yaml

    # 2. Configuration & Secrets (Apply before Apps)
    - k3s-secrets/backend-secrets-dev.yaml
    - k3s-secrets/resend-secrets-dev.yaml
    - platform-core/mqtt/mosquitto-config.yaml

    # 3. Applications (Deployments & Services)
    - platform-core/mqtt/mosquitto-dev.yaml
    - platform-apps/chatter/frontend/frontend-dev.yaml
    - platform-apps/chatter/backend/backend-dev.yaml
    - platform-services/resend

    # 4. Networking (Routes & Permissions)
    - platform-core/mqtt/mqtt-route.yaml
    - platform-core/mqtt/reference-grant.yaml
    - platform-apps/chatter/frontend/frontend-route.yaml
    - platform-apps/chatter/backend/backend-route.yaml
deploy:
  kubectl: {}