apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: chatter-dev
type: Opaque
stringData:


  #MONGODB_ATLAS
  MONGODB_URI: "MONGO DB Atlas connection string here"
  #PORT
  PORT: "3000"

