---

# PLAY 1: Run the Provisioning (Imported)
- name: "Nuke and Reinstall VPS"
  ansible.builtin.import_playbook: 00-infra-bootstrap/recreate-vps.yml

- name: "Preflight ssh test"
  ansible.builtin.import_playbook: 00-infra-bootstrap/preflight.yml

# reload new values for PLAY 3
- name: "Refresh Inventory to pick up the new IP"
  hosts: localhost
  tasks:
    - name: "Reload inventory file from disk"
      ansible.builtin.meta: refresh_inventory

# PLAY 2: Run the Setup (Imported)
- name: "System prep and Hardening"
  ansible.builtin.import_playbook: 00-infra-bootstrap/system-prep.yml

# reload new values for PLAY 4
- name: "Refresh Inventory to pick up the new IP"
  hosts: localhost
  tasks:
    - name: "Reload inventory file from disk"
      ansible.builtin.meta: refresh_inventory

# PLAY 3: K3s installation (Imported)
- name: "K3s Installation"
  ansible.builtin.import_playbook: 00-infra-bootstrap/k3s-install.yml

