apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateways-to-mqtt
  namespace: mqtt-infra
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: chatter-dev    # Allows routes in chatter-dev
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: nginx-gateway  # Allows routes in nginx-gateway
  to:
    - group: ""
      kind: Service
      # name: mosquitto-internal # You can be specific or remove 'name' to allow all services in this ns